<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="qrichtext" content="1" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'Consolas'; font-size:10pt; font-weight:400; font-style:normal;">
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Type &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.</p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">IPython 8.15.0 -- An enhanced Interactive Python.</p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#00ff00;">In [</span><span style=" font-weight:600; color:#00ff00;">1</span><span style=" color:#00ff00;">]:</span> pip install streamlit-option-menu</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Note: you may need to restart the kernel to use updated packages.Collecting streamlit-option-menu</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">  Obtaining dependency information for streamlit-option-menu from https://files.pythonhosted.org/packages/5b/7b/6fcab37664539e1a78f12f53002e0a15eb67dd009f540e60f0228e01760e/streamlit_option_menu-0.3.6-py3-none-any.whl.metadata</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">  Downloading streamlit_option_menu-0.3.6-py3-none-any.whl.metadata (2.5 kB)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: streamlit&gt;=0.63 in c:\users\ac\anaconda3\lib\site-packages (from streamlit-option-menu) (1.27.2)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: altair&lt;6,&gt;=4.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (5.1.2)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: blinker&lt;2,&gt;=1.0.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (1.6.3)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: cachetools&lt;6,&gt;=4.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (5.3.1)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: click&lt;9,&gt;=7.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (8.0.4)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: importlib-metadata&lt;7,&gt;=1.4 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (6.0.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: numpy&lt;2,&gt;=1.19.3 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (1.24.3)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: packaging&lt;24,&gt;=16.8 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (23.1)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: pandas&lt;3,&gt;=1.3.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (2.0.3)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: pillow&lt;11,&gt;=7.1.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (9.4.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: protobuf&lt;5,&gt;=3.20 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (4.24.4)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: pyarrow&gt;=6.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (11.0.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: python-dateutil&lt;3,&gt;=2.7.3 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (2.8.2)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: requests&lt;3,&gt;=2.27 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (2.31.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: rich&lt;14,&gt;=10.14.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (13.6.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: tenacity&lt;9,&gt;=8.1.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (8.2.2)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: toml&lt;2,&gt;=0.10.1 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (0.10.2)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: typing-extensions&lt;5,&gt;=4.3.0 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (4.7.1)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: tzlocal&lt;6,&gt;=1.1 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (5.1)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: validators&lt;1,&gt;=0.2 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (0.22.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: gitpython!=3.1.19,&lt;4,&gt;=3.0.7 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (3.1.37)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: pydeck&lt;1,&gt;=0.8.0b4 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (0.8.1b0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: tornado&lt;7,&gt;=6.0.3 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (6.3.2)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: watchdog&gt;=2.1.5 in c:\users\ac\anaconda3\lib\site-packages (from streamlit&gt;=0.63-&gt;streamlit-option-menu) (2.1.6)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: jinja2 in c:\users\ac\anaconda3\lib\site-packages (from altair&lt;6,&gt;=4.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (3.1.2)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: jsonschema&gt;=3.0 in c:\users\ac\anaconda3\lib\site-packages (from altair&lt;6,&gt;=4.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (4.17.3)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: toolz in c:\users\ac\anaconda3\lib\site-packages (from altair&lt;6,&gt;=4.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (0.12.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: colorama in c:\users\ac\anaconda3\lib\site-packages (from click&lt;9,&gt;=7.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (0.4.6)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: gitdb&lt;5,&gt;=4.0.1 in c:\users\ac\anaconda3\lib\site-packages (from gitpython!=3.1.19,&lt;4,&gt;=3.0.7-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (4.0.10)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: zipp&gt;=0.5 in c:\users\ac\anaconda3\lib\site-packages (from importlib-metadata&lt;7,&gt;=1.4-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (3.11.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: pytz&gt;=2020.1 in c:\users\ac\anaconda3\lib\site-packages (from pandas&lt;3,&gt;=1.3.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (2023.3.post1)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: tzdata&gt;=2022.1 in c:\users\ac\anaconda3\lib\site-packages (from pandas&lt;3,&gt;=1.3.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (2023.3)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: six&gt;=1.5 in c:\users\ac\anaconda3\lib\site-packages (from python-dateutil&lt;3,&gt;=2.7.3-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (1.16.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: charset-normalizer&lt;4,&gt;=2 in c:\users\ac\anaconda3\lib\site-packages (from requests&lt;3,&gt;=2.27-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (2.0.4)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: idna&lt;4,&gt;=2.5 in c:\users\ac\anaconda3\lib\site-packages (from requests&lt;3,&gt;=2.27-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (3.4)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: urllib3&lt;3,&gt;=1.21.1 in c:\users\ac\anaconda3\lib\site-packages (from requests&lt;3,&gt;=2.27-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (1.26.16)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: certifi&gt;=2017.4.17 in c:\users\ac\anaconda3\lib\site-packages (from requests&lt;3,&gt;=2.27-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (2023.7.22)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: markdown-it-py&gt;=2.2.0 in c:\users\ac\anaconda3\lib\site-packages (from rich&lt;14,&gt;=10.14.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (2.2.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: pygments&lt;3.0.0,&gt;=2.13.0 in c:\users\ac\anaconda3\lib\site-packages (from rich&lt;14,&gt;=10.14.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (2.15.1)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: smmap&lt;6,&gt;=3.0.1 in c:\users\ac\anaconda3\lib\site-packages (from gitdb&lt;5,&gt;=4.0.1-&gt;gitpython!=3.1.19,&lt;4,&gt;=3.0.7-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (5.0.1)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: MarkupSafe&gt;=2.0 in c:\users\ac\anaconda3\lib\site-packages (from jinja2-&gt;altair&lt;6,&gt;=4.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (2.1.1)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: attrs&gt;=17.4.0 in c:\users\ac\anaconda3\lib\site-packages (from jsonschema&gt;=3.0-&gt;altair&lt;6,&gt;=4.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (22.1.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,&gt;=0.14.0 in c:\users\ac\anaconda3\lib\site-packages (from jsonschema&gt;=3.0-&gt;altair&lt;6,&gt;=4.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (0.18.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Requirement already satisfied: mdurl~=0.1 in c:\users\ac\anaconda3\lib\site-packages (from markdown-it-py&gt;=2.2.0-&gt;rich&lt;14,&gt;=10.14.0-&gt;streamlit&gt;=0.63-&gt;streamlit-option-menu) (0.1.0)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Downloading streamlit_option_menu-0.3.6-py3-none-any.whl (799 kB)</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------------- 0.0/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    --------------------------------------- 10.2/799.2 kB ? eta -:--:--</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   - -------------------------------------- 30.7/799.2 kB 29.1 kB/s eta 0:00:27</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   - -------------------------------------- 30.7/799.2 kB 29.1 kB/s eta 0:00:27</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   - -------------------------------------- 30.7/799.2 kB 29.1 kB/s eta 0:00:27</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   - -------------------------------------- 30.7/799.2 kB 29.1 kB/s eta 0:00:27</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   - -------------------------------------- 30.7/799.2 kB 29.1 kB/s eta 0:00:27</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -- ------------------------------------- 41.0/799.2 kB 32.2 kB/s eta 0:00:24</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 61.4/799.2 kB 33.4 kB/s eta 0:00:23</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 61.4/799.2 kB 33.4 kB/s eta 0:00:23</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 61.4/799.2 kB 33.4 kB/s eta 0:00:23</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 61.4/799.2 kB 33.4 kB/s eta 0:00:23</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 61.4/799.2 kB 33.4 kB/s eta 0:00:23</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 61.4/799.2 kB 33.4 kB/s eta 0:00:23</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 71.7/799.2 kB 33.9 kB/s eta 0:00:22</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 71.7/799.2 kB 33.9 kB/s eta 0:00:22</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 71.7/799.2 kB 33.9 kB/s eta 0:00:22</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 71.7/799.2 kB 33.9 kB/s eta 0:00:22</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --- ------------------------------------ 71.7/799.2 kB 33.9 kB/s eta 0:00:22</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---- ----------------------------------- 92.2/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---- ----------------------------------- 92.2/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---- ----------------------------------- 92.2/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---- ----------------------------------- 92.2/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---- ----------------------------------- 92.2/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---- ----------------------------------- 92.2/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---- ----------------------------------- 92.2/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 112.6/799.2 kB 42.8 kB/s eta 0:00:17</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 122.9/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 122.9/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----- --------------------------------- 122.9/799.2 kB 39.4 kB/s eta 0:00:18</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------ -------------------------------- 143.4/799.2 kB 44.8 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------ -------------------------------- 143.4/799.2 kB 44.8 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------ -------------------------------- 143.4/799.2 kB 44.8 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------ -------------------------------- 143.4/799.2 kB 44.8 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------- ------------------------------- 153.6/799.2 kB 45.2 kB/s eta 0:00:15</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------- ------------------------------ 174.1/799.2 kB 45.6 kB/s eta 0:00:14</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------- ------------------------------ 174.1/799.2 kB 45.6 kB/s eta 0:00:14</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------- ------------------------------ 174.1/799.2 kB 45.6 kB/s eta 0:00:14</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------- ------------------------------ 174.1/799.2 kB 45.6 kB/s eta 0:00:14</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------- ------------------------------ 174.1/799.2 kB 45.6 kB/s eta 0:00:14</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------- ------------------------------ 174.1/799.2 kB 45.6 kB/s eta 0:00:14</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------- ------------------------------ 174.1/799.2 kB 45.6 kB/s eta 0:00:14</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------- ------------------------------ 174.1/799.2 kB 45.6 kB/s eta 0:00:14</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------- ----------------------------- 194.6/799.2 kB 46.6 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------- ----------------------------- 204.8/799.2 kB 48.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------- ----------------------------- 204.8/799.2 kB 48.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------- ----------------------------- 204.8/799.2 kB 48.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------- ----------------------------- 204.8/799.2 kB 48.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------- ----------------------------- 204.8/799.2 kB 48.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------- ----------------------------- 204.8/799.2 kB 48.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------- ----------------------------- 204.8/799.2 kB 48.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------- ---------------------------- 225.3/799.2 kB 49.3 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------- ---------------------------- 225.3/799.2 kB 49.3 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------- ---------------------------- 225.3/799.2 kB 49.3 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------- ---------------------------- 225.3/799.2 kB 49.3 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------- ---------------------------- 225.3/799.2 kB 49.3 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------- --------------------------- 235.5/799.2 kB 49.0 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------- --------------------------- 235.5/799.2 kB 49.0 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------- --------------------------- 235.5/799.2 kB 49.0 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------- --------------------------- 235.5/799.2 kB 49.0 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------- --------------------------- 235.5/799.2 kB 49.0 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------ -------------------------- 256.0/799.2 kB 50.9 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 276.5/799.2 kB 50.0 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------- ------------------------- 286.7/799.2 kB 47.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------- ------------------------ 307.2/799.2 kB 38.5 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------- ------------------------ 307.2/799.2 kB 38.5 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------- ----------------------- 317.4/799.2 kB 39.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------- ----------------------- 317.4/799.2 kB 39.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------- ----------------------- 317.4/799.2 kB 39.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------- ----------------------- 317.4/799.2 kB 39.1 kB/s eta 0:00:13</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------- ---------------------- 337.9/799.2 kB 40.8 kB/s eta 0:00:12</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------- --------------------- 358.4/799.2 kB 43.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------- --------------------- 358.4/799.2 kB 43.1 kB/s eta 0:00:11</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------ -------------------- 389.1/799.2 kB 46.4 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 399.4/799.2 kB 47.3 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 399.4/799.2 kB 47.3 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 399.4/799.2 kB 47.3 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 399.4/799.2 kB 47.3 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 399.4/799.2 kB 47.3 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 399.4/799.2 kB 47.3 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 399.4/799.2 kB 47.3 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 399.4/799.2 kB 47.3 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 409.6/799.2 kB 46.5 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 409.6/799.2 kB 46.5 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 409.6/799.2 kB 46.5 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 409.6/799.2 kB 46.5 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------- ------------------- 409.6/799.2 kB 46.5 kB/s eta 0:00:09</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------------- ------------------ 430.1/799.2 kB 47.6 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------------- ------------------ 430.1/799.2 kB 47.6 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------------- ------------------ 430.1/799.2 kB 47.6 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------------- ------------------ 430.1/799.2 kB 47.6 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------------- ------------------ 430.1/799.2 kB 47.6 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------------- ------------------ 430.1/799.2 kB 47.6 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------- ----------------- 450.6/799.2 kB 48.3 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------- ----------------- 450.6/799.2 kB 48.3 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------- ----------------- 450.6/799.2 kB 48.3 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------- ----------------- 450.6/799.2 kB 48.3 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------- ----------------- 450.6/799.2 kB 48.3 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------- ---------------- 460.8/799.2 kB 48.1 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------- ---------------- 460.8/799.2 kB 48.1 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------- ---------------- 460.8/799.2 kB 48.1 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------- ---------------- 460.8/799.2 kB 48.1 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------- ---------------- 460.8/799.2 kB 48.1 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------- ---------------- 460.8/799.2 kB 48.1 kB/s eta 0:00:08</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------- --------------- 481.3/799.2 kB 48.8 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------------ -------------- 512.0/799.2 kB 41.6 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------------ -------------- 512.0/799.2 kB 41.6 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------------ -------------- 512.0/799.2 kB 41.6 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ------------------------- ------------- 532.5/799.2 kB 42.5 kB/s eta 0:00:07</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------------------- ------------ 542.7/799.2 kB 43.1 kB/s eta 0:00:06</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   -------------------------- ------------ 542.7/799.2 kB 43.1 kB/s eta 0:00:06</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------------- ----------- 573.4/799.2 kB 45.0 kB/s eta 0:00:06</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------------- ----------- 573.4/799.2 kB 45.0 kB/s eta 0:00:06</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------- ---------- 593.9/799.2 kB 46.3 kB/s eta 0:00:05</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------- ---------- 593.9/799.2 kB 46.3 kB/s eta 0:00:05</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------- ---------- 593.9/799.2 kB 46.3 kB/s eta 0:00:05</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------- ---------- 593.9/799.2 kB 46.3 kB/s eta 0:00:05</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------- ---------- 593.9/799.2 kB 46.3 kB/s eta 0:00:05</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------- ---------- 593.9/799.2 kB 46.3 kB/s eta 0:00:05</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------- --------- 614.4/799.2 kB 46.8 kB/s eta 0:00:04</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 706.6/799.2 kB 45.4 kB/s eta 0:00:03</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 716.8/799.2 kB 43.3 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 716.8/799.2 kB 43.3 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 716.8/799.2 kB 43.3 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 716.8/799.2 kB 43.3 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ---------------------------------- ---- 716.8/799.2 kB 43.3 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------------- --- 737.3/799.2 kB 44.0 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------------- --- 737.3/799.2 kB 44.0 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------------- --- 737.3/799.2 kB 44.0 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   ----------------------------------- --- 737.3/799.2 kB 44.0 kB/s eta 0:00:02</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------------------------  798.7/799.2 kB 47.0 kB/s eta 0:00:01</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   --------------------------------------- 799.2/799.2 kB 47.0 kB/s eta 0:00:00</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Installing collected packages: streamlit-option-menu</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Successfully installed streamlit-option-menu-0.3.6</p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#00ff00;">In [</span><span style=" font-weight:600; color:#00ff00;">2</span><span style=" color:#00ff00;">]:</span> streamlit run projectweb.py</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#00ffff;">  Cell </span><span style=" color:#00ff00;">In[2], line 1</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#ffff00;">    streamlit run projectweb.py</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#ffffff;">              ^</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#ff0000;">SyntaxError:</span> invalid syntax</p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#00ff00;">In [</span><span style=" font-weight:600; color:#00ff00;">3</span><span style=" color:#00ff00;">]:</span> </p></body></html>